/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package projectoop;

import javax.swing.JOptionPane;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.text.*;
import java.awt.print.*;
import java.awt.event.*;
import java.awt.*;




/**
 *
 * @author Lotfar Kaes
// */

/*
 * Developed at Kristianstad University with Combitech AB 
 * URL: http://www.hkr.se
 */

import java.sql.*;
import javax.swing.*;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class admin extends javax.swing.JFrame {

    Connection con;
    ResultSet rs;
    PreparedStatement pst;
    static String sql;
    private String[] args;

   

    public admin() {
        initComponents();
        Currentdate();
    }

    public void Currentdate() {
        Calendar cal = new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        date.setText(year + "/" + (month + 1) + "/" + day);

        int second = cal.get(Calendar.SECOND);
        int minute = cal.get(Calendar.MINUTE);
        int hour = cal.get(Calendar.HOUR);
        time.setText(hour + ":" + (minute) + ":" + second);

    }

    public void close() {
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        welcome21 = new projectoop.welcome2();
        searchButton = new javax.swing.JRadioButton();
        personButton = new javax.swing.JRadioButton();
        nameLabel = new javax.swing.JLabel();
        companyLabel = new javax.swing.JLabel();
        searchname = new javax.swing.JTextField();
        searchcompany = new javax.swing.JTextField();
        resultLabel = new javax.swing.JLabel();
        showall = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        p1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jbutton3 = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        searchdate = new javax.swing.JTextField();
        tosearchdate = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        namlabel = new javax.swing.JLabel();
        comlabel = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 1044));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        buttonGroup1.add(searchButton);
        searchButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        searchButton.setForeground(new java.awt.Color(0, 204, 0));
        searchButton.setText("Search Date");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(personButton);
        personButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        personButton.setForeground(new java.awt.Color(0, 204, 0));
        personButton.setText("Search Person");
        personButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personButtonActionPerformed(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(204, 0, 204));
        nameLabel.setText("Name");

        companyLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        companyLabel.setForeground(new java.awt.Color(102, 51, 255));
        companyLabel.setText("Company");

        searchname.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        searchname.setForeground(new java.awt.Color(204, 0, 204));
        searchname.setToolTipText("search name ");
        searchname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchnameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchnameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchnameMouseExited(evt);
            }
        });
        searchname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchnameActionPerformed(evt);
            }
        });

        searchcompany.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        searchcompany.setForeground(new java.awt.Color(102, 51, 255));
        searchcompany.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchcompanyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchcompanyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchcompanyMouseExited(evt);
            }
        });
        searchcompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchcompanyActionPerformed(evt);
            }
        });

        resultLabel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        resultLabel.setForeground(new java.awt.Color(255, 0, 0));
        resultLabel.setText("Search Result");

        showall.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        showall.setForeground(new java.awt.Color(255, 51, 51));
        showall.setText("Show All");
        showall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showallActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectoop/Combitech2.jpg"))); // NOI18N
        jLabel5.setText("jLabel1");

        table.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial number", "Date", "Time", "Name", "ID/Passoprt", "country", "Checked by", "Company", "Visitor_attendent"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        p1.add(jScrollPane1);
        jScrollPane1.setBounds(40, 60, 1158, 240);

        jbutton3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jbutton3.setForeground(new java.awt.Color(255, 0, 0));
        jbutton3.setText("Print Result");
        jbutton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton3ActionPerformed(evt);
            }
        });
        p1.add(jbutton3);
        jbutton3.setBounds(990, 320, 150, 33);

        delete.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        delete.setForeground(new java.awt.Color(204, 0, 204));
        delete.setText("Delete");
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 0, 204));
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        searchdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        searchdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchdateMouseClicked(evt);
            }
        });
        searchdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchdateActionPerformed(evt);
            }
        });

        tosearchdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tosearchdateMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("From");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setText("To");

        jButton1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 51, 255));
        jButton1.setText("Databse Setting ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        namlabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        namlabel.setForeground(new java.awt.Color(153, 0, 0));

        comlabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comlabel.setForeground(new java.awt.Color(255, 51, 102));

        date.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        date.setForeground(new java.awt.Color(255, 102, 0));
        date.setText("Date");

        time.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        time.setForeground(new java.awt.Color(0, 204, 51));
        time.setText("Time");

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 51));
        jLabel7.setText("Time");

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 0));
        jLabel8.setText("Date");

        jButton3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 0, 204));
        jButton3.setText("Refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchButton)
                            .addComponent(searchdate, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(personButton)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameLabel)
                                    .addComponent(companyLabel))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(searchname, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(searchcompany, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(showall))
                                    .addComponent(comlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(namlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(34, 34, 34)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(69, 69, 69)
                                .addComponent(delete)
                                .addGap(109, 109, 109)
                                .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(28, 28, 28)
                                .addComponent(tosearchdate, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 1249, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addComponent(jButton3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18)
                                    .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(time, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addComponent(personButton)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchcompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(companyLabel))
                        .addGap(3, 3, 3)
                        .addComponent(comlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(showall))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButton3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(searchButton)
                                        .addGap(116, 116, 116))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(searchdate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(55, 55, 55)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tosearchdate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(delete))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel5)
                .addGap(270, 270, 270))
        );

        searchcompany.getAccessibleContext().setAccessibleDescription("search by company ");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void personButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personButtonActionPerformed
       jLabel1.setVisible(false);
        searchdate.setVisible(false);
          jLabel6.setVisible(false);
        tosearchdate.setVisible(false);
        
    }//GEN-LAST:event_personButtonActionPerformed

    
    
    
    
    
    
    private void searchnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchnameActionPerformed

    private void searchcompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchcompanyActionPerformed
        // TODO add your handling code he      
    }//GEN-LAST:event_searchcompanyActionPerformed
      int a=0;
    private void showallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showallActionPerformed
        // TODO add your handling code here:
      
        
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        if(a==0){
        try {

            Class.forName("com.mysql.jdbc.Driver").newInstance();
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/visitor_info", "root", "root");
            Statement st = con.createStatement();
            System.out.println("Connected");

         //   JOptionPane.showMessageDialog(this, "Connection succesful");

            String sql = ("select info.id,info.date,info.time, info.name ,table2.pnrpassport,table2.Check_by,info.company,info.country,info.visitor_attendent from info,table2 where info.id = table2.idtable2 ;");
;
              a++;


            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {

                String d1 = rs.getString("id");
                String d2 = rs.getString("date");
                String d3 = rs.getString("time");
                String d4 = rs.getString("name");
                String d5 = rs.getString("pnrpassport");
                String d6 = rs.getString("country");
                String d7 = rs.getString("Check_by");
                String d8 = rs.getString("company");
                String d9 = rs.getString("visitor_attendent");
                model.addRow(new Object[]{d1, d2, d3, d4, d5, d6, d7, d8, d9});
                
                
            }

        } catch (Exception ex) {
            System.out.println("Failed to connect." + ex);
            JOptionPane.showMessageDialog(this, "Error in connection");
        }
}
    }//GEN-LAST:event_showallActionPerformed
 
 int b=0;
    private void searchnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchnameMouseClicked
        // TODO add your handling code here:
        
        String nam= searchname.getText();
        
        
        if(!nam.equals("")){
          DefaultTableModel model = (DefaultTableModel) table.getModel();
          if (b==0){
        try {

            Class.forName("com.mysql.jdbc.Driver").newInstance();
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/visitor_info", "root", "root");
            Statement st = con.createStatement();
            System.out.println("Connected");



  String sql=("select info.id,info.date,info.time,info.name ,table2.pnrpassport,table2.Check_by,info.company,info.country,info.visitor_attendent from info,table2 where info.name = " + "'" + nam + "'" + " && info.id = table2.idtable2 ;") ;
            b++;

            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {

           
                String d1 = rs.getString("id");
                String d2 = rs.getString("date");
                String d3 = rs.getString("time");
                String d4 = rs.getString("name");
                String d5 = rs.getString("pnrpassport");
                String d6 = rs.getString("country");
                String d7 = rs.getString("Check_by");
                String d8 = rs.getString("company");
                String d9 = rs.getString("visitor_attendent");
                model.addRow(new Object[]{d1, d2, d3, d4, d5, d6, d7, d8, d9});
                
                
            }

        } catch (Exception ex) {
            System.out.println("Failed to connect." + ex);
            JOptionPane.showMessageDialog(this, "Error in connection");
        }
        
        }
        }
    }//GEN-LAST:event_searchnameMouseClicked

    int c=0;
    private void searchcompanyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchcompanyMouseClicked
        // TODO add your handling code here:
        
        String com= searchcompany.getText();
        
        if(!com.equals("")){
          DefaultTableModel model = (DefaultTableModel) table.getModel();
          if (c==0){
        try {

            Class.forName("com.mysql.jdbc.Driver").newInstance();
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/visitor_info", "root", "root");
            Statement st = con.createStatement();
            System.out.println("Connected");

//            JOptionPane.showMessageDialog(this, "Connection succesful");

   String sql=("select info.id,info.date,info.time,info.name ,table2.pnrpassport,table2.Check_by,info.company,info.country,info.visitor_attendent from info,table2 where info.company = " + "'" + com + "'" + " && info.id = table2.idtable2 ;") ;

                c++;
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {

                
                String d1 = rs.getString("id");
                String d2 = rs.getString("date");
                String d3 = rs.getString("time");
                String d4 = rs.getString("name");
                String d5 = rs.getString("pnrpassport");
                String d6 = rs.getString("country");
                String d7 = rs.getString("Check_by");
                String d8 = rs.getString("company");
                String d9 = rs.getString("visitor_attendent");
                model.addRow(new Object[]{d1, d2, d3, d4, d5, d6, d7, d8, d9});
                
                
                
                
            }

        } catch (Exception ex) {
            System.out.println("Failed to connect." + ex);
            JOptionPane.showMessageDialog(this, "Error in connection");
        }
          }
        }
    }//GEN-LAST:event_searchcompanyMouseClicked

    
    
    
    
    
    
    
    
    
    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
     
                                                  
       DefaultTableModel model = (DefaultTableModel) table.getModel();
       int numberOfRows = table.getSelectedRows().length;
        try {
                  //String d1 = rs.getString("username");
                  //String d2 = rs.getString("password");
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/login", "root", "root");
            Statement st = con.createStatement();
            System.out.println("deleted");
             for(int i=0;i<numberOfRows;i++){
             model.removeRow(table.getSelectedRow());
             
             
             }


        } catch (Exception ex) {
            System.out.println("Failed to connect." + ex);
            JOptionPane.showMessageDialog(this, "Error in connection");
        }
        
        
        
   
    }//GEN-LAST:event_deleteActionPerformed

  
    
    
    
    
    private void jbutton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton3ActionPerformed
        // TODO add your handling code here:
        
        PrinterTest test = new PrinterTest();
         String[] args = null;
        PrinterTest.main(args);
        
        MessageFormat header = new MessageFormat ("Search result");
        MessageFormat footer = new MessageFormat ("Page {0,number, integer}");
        
        
        try {
            table.print(JTable.PrintMode.NORMAL,header,footer);
            
        }catch  (java.awt.print.PrinterException e){
            System.err.format("cannot print %s%n", e .getMessage());
       
        }
        
        
        
        
    }//GEN-LAST:event_jbutton3ActionPerformed

     

    
    
    
    
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
      
         String searh= searchdate.getText();
        
        
        if(!searh.equals("")){
          DefaultTableModel model = (DefaultTableModel) table.getModel();
         
        try {

            Class.forName("com.mysql.jdbc.Driver").newInstance();
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/visitor_info", "root", "root");
            Statement st = con.createStatement();
            System.out.println("Connected");



  String sql=("select info.id,info.date,info.time,info.name ,table2.pnrpassport,table2.Check_by,info.company,info.country,info.visitor_attendent from info,table2 where info.date = " + "'" + searh + "'" + " && info.id = table2.idtable2 ;") ;
        

            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {

           
                String d1 = rs.getString("id");
                String d2 = rs.getString("date");
                String d3 = rs.getString("time");
                String d4 = rs.getString("name");
                String d5 = rs.getString("pnrpassport");
                String d6 = rs.getString("country");
                String d7 = rs.getString("Check_by");
                String d8 = rs.getString("company");
                String d9 = rs.getString("visitor_attendent");
                model.addRow(new Object[]{d1, d2, d3, d4, d5, d6, d7, d8, d9});
                
                
            }

        } catch (Exception ex) {
            System.out.println("Failed to connect." + ex);
            JOptionPane.showMessageDialog(this, "Error in connection");
        }
        
        }
        
   
       
    }//GEN-LAST:event_formMouseClicked

    
    int s=0;
    private void searchdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchdateMouseClicked
         
         String searh= searchdate.getText();
        
        
        if(!searh.equals("")){
          DefaultTableModel model = (DefaultTableModel) table.getModel();
         if(s==0){
        try {

            Class.forName("com.mysql.jdbc.Driver").newInstance();
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/visitor_info", "root", "root");
            Statement st = con.createStatement();
            System.out.println("Connected");



  String sql=("select info.id,info.date,info.time,info.name ,table2.pnrpassport,table2.Check_by,info.company,info.country,info.visitor_attendent from info,table2 where info.date = " + "'" + searh + "'" + " && info.id = table2.idtable2 ;") ;
            s++;

            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {

           
                String d1 = rs.getString("id");
                String d2 = rs.getString("date");
                String d3 = rs.getString("time");
                String d4 = rs.getString("name");
                String d5 = rs.getString("pnrpassport");
                String d6 = rs.getString("country");
                String d7 = rs.getString("Check_by");
                String d8 = rs.getString("company");
                String d9 = rs.getString("visitor_attendent");
                model.addRow(new Object[]{d1, d2, d3, d4, d5, d6, d7, d8, d9});
                
                
            }

        } catch (Exception ex) {
            System.out.println("Failed to connect." + ex);
            JOptionPane.showMessageDialog(this, "Error in connection");
        }
        
        }
        
   
       
        }
    }//GEN-LAST:event_searchdateMouseClicked

    
    
    
    
    
    
    
    
    private void searchdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchdateActionPerformed

    
    int to=0;
    private void tosearchdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tosearchdateMouseClicked
         String searh= tosearchdate.getText();
        
        
        if(!searh.equals("")){
          DefaultTableModel model = (DefaultTableModel) table.getModel();
         if(to==0){
        try {

            Class.forName("com.mysql.jdbc.Driver").newInstance();
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/visitor_info", "root", "root");
            Statement st = con.createStatement();
            System.out.println("Connected");



  String sql=("select info.id,info.date,info.time,info.name ,table2.pnrpassport,table2.Check_by,info.company,info.country,info.visitor_attendent from info,table2 where info.date = " + "'" + searh + "'" + " && info.id = table2.idtable2 ;") ;
            to++;

            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {

           
                String d1 = rs.getString("id");
                String d2 = rs.getString("date");
                String d3 = rs.getString("time");
                String d4 = rs.getString("name");
                String d5 = rs.getString("pnrpassport");
                String d6 = rs.getString("country");
                String d7 = rs.getString("Check_by");
                String d8 = rs.getString("company");
                String d9 = rs.getString("visitor_attendent");
                model.addRow(new Object[]{d1, d2, d3, d4, d5, d6, d7, d8, d9});
                
                
            }

        } catch (Exception ex) {
            System.out.println("Failed to connect." + ex);
            JOptionPane.showMessageDialog(this, "Error in connection");
        }
        
        }
        
   
       
        }
    }//GEN-LAST:event_tosearchdateMouseClicked

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
       
        
      
    }//GEN-LAST:event_deleteMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
//          DefaultTableModel model = (DefaultTableModel) table.getModel();
//       int numberOfRows = table.getSelectedRows().length;
//       
//        try {
//                  //String d1 = rs.getString("username");
//                 
//            Class.forName("com.mysql.jdbc.Driver").newInstance();
//            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/visitor_info", "root", "root");
//            Statement st = con.createStatement();
//            
//             //String d9 = rs.getString("visitor_attendent");
////             System.out.println("deleted");
////             for(int i=0;i<numberOfRows;i++){
////             
////             model.removeRow(table.getSelectedRow());
////             }
//             int column = table.getSelectedColumn();
//             int row = table.getSelectedRow();
//             
//             Object ob1=JOptionPane.showInputDialog("Enter the new visitor atttendent");
////             Object ob =model.getValueAt(row, column);
////             ob=ob1;
//            // System.out.println(ob);
//           int record;
//            String sql = "update info set visitor_attendent = " + "'" + ob1 + "'" + " where visitor_attendent = "+ "'"+row+"'"  ;
//           record = st.executeUpdate(sql);
//             //            System.out.println("");
////             for(int i=0;i<numberOfRows;i++){
////             
////                model.removeRow(table.getSelectedRow());
////                Object[] Column = new Object[] {model};
////                model.addColumn(table.getSelectedRow());;
//          //   }
//
// 

//
//
//   if(e.getSource()==jButton1){
//
//
//
//               table.getModel().addTableModelListener(new TableModelListener() {
//  public void tableChanged(TableModelEvent e) {
////      myDbConnection dbconnect;
//    dbconnect = new myDbConnection();

//      
//       Class.forName("com.mysql.jdbc.Driver").newInstance();
//            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/visitor_info", "root", "root");
//           Statement st = con.createStatement();
//         ResultSet resultSet =null;
//        resultSet = dbconnect.excuteQuery("SELECT id, area,location, status1 FROM pledges ");
//       int row = e.getFirstRow();
//    int column = e.getColumn();
//    TableModel model = (TableModel)e.getSource();
//    String columnName = model.getColumnName(column);
//    Object data = model.getValueAt(row, column);
//    int viewRow = table.getSelectedRow(); // view row with sort
//    int modelRow = table.convertRowIndexToModel(viewRow); // convert
//    dbconnect.excuteUpdate("update pledges set area ='" + data + "' where id = '"+table.getModel().getValueAt(modelRow,0) +"'"  );
//      System.out.println("Table value changed "+data);
//  } 
//});
//       
//        } catch (Exception ex) {
//            System.out.println("Failed to connect." + ex);
//            JOptionPane.showMessageDialog(this, "Error in connection");
//        
//        
//        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

     database_setting oob = new database_setting();
        String[] args = null;
        database_setting.main(args);
close();        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed

        nameLabel.setVisible(true);
        searchname.setVisible(true);
        companyLabel.setVisible(true);
        searchcompany.setVisible(true);

    }//GEN-LAST:event_searchButtonActionPerformed

    private void searchnameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchnameMouseEntered
        // TODO add your handling code here:
        
          namlabel.setText("Enter the name you want to search");
    }//GEN-LAST:event_searchnameMouseEntered

    private void searchnameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchnameMouseExited
        // TODO add your handling code here:
        
          namlabel.setText("  ");
        
    }//GEN-LAST:event_searchnameMouseExited

    private void searchcompanyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchcompanyMouseEntered
        // TODO add your handling code here:
        
          comlabel.setText("Enter the Company want to search");
    }//GEN-LAST:event_searchcompanyMouseEntered

    private void searchcompanyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchcompanyMouseExited
        // TODO add your handling code here:
         comlabel.setText("  ");
        
    }//GEN-LAST:event_searchcompanyMouseExited

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        admin ii = new admin();
        ii.main(args);
        close();
    }//GEN-LAST:event_jButton3ActionPerformed
 
   
                                        
        // TODO add your handling code here:
        
       
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new admin().setVisible(true);



            }
        });
    }
    private javax.swing.JComboBox country;
    public static javax.swing.JTextField company;
    private javax.swing.JComboBox reception;
    private javax.swing.JTextField idpass;
    public static javax.swing.JTextField name;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel comlabel;
    public static javax.swing.JLabel companyLabel;
    private javax.swing.JLabel date;
    private javax.swing.JButton delete;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable4;
    private javax.swing.JButton jbutton3;
    public static javax.swing.JLabel nameLabel;
    private javax.swing.JLabel namlabel;
    private javax.swing.JDesktopPane p1;
    public javax.swing.JRadioButton personButton;
    private javax.swing.JLabel resultLabel;
    public javax.swing.JRadioButton searchButton;
    public static javax.swing.JTextField searchcompany;
    private javax.swing.JTextField searchdate;
    public static javax.swing.JTextField searchname;
    private javax.swing.JButton showall;
    private javax.swing.JTable table;
    private javax.swing.JLabel time;
    private javax.swing.JTextField tosearchdate;
    private projectoop.welcome2 welcome21;
    // End of variables declaration//GEN-END:variables
}
