/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package projectoop;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.*;

import java.util.Calendar;
import java.util.GregorianCalendar;
import java.awt.event.*;
import java.awt.*;

//import net.proteanit.sql.DbUtils;

/**
 *
 * @author Lotfar Kaes
// */

/*
 * Developed at Kristianstad University with Combitech AB 
 * URL: http://www.hkr.se
 */

public class visitor extends javax.swing.JFrame {

    Connection con;
    ResultSet rs;
    PreparedStatement pst;
    static String sql;
    String dat,tim;
    private String[] args;

    /**
     * Creates new form visitor
     */
    public visitor() {
        initComponents();
        Currentdate();
    }

    
    public void Currentdate(){
        Calendar cal = new GregorianCalendar ();
        int month =cal.get( Calendar.MONTH);
        String mon=Integer.toString(month);
        int year =cal.get( Calendar.YEAR);
         String yea=Integer.toString(year);
        int day =cal.get( Calendar.DAY_OF_MONTH);
         String da=Integer.toString(day);
          dat=year+"/"+(month+1)+"/"+day;
        
         date.setText(year+"/"+(month+1)+"/"+day);
        
         int second =cal.get( Calendar.SECOND);
         String sec=Integer.toString(second);
        int minute =cal.get( Calendar.MINUTE);
        String min=Integer.toString(minute);
        int hour =cal.get( Calendar.HOUR);
        String hou=Integer.toString(hour);
        tim=hour+":"+(minute)+":"+second;
        time.setText(hour+":"+(minute)+":"+second);
        
    }
    
    public void close(){
    WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    
     
}
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        finishButton = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        company = new javax.swing.JTextField();
        NameLabel = new javax.swing.JLabel();
        companyLabel = new javax.swing.JLabel();
        countryLabel = new javax.swing.JLabel();
        visitorLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        reception = new javax.swing.JComboBox();
        country = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        adminButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        namsuggestion = new javax.swing.JLabel();
        companySuggestion = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jMenuItem1.setText("Visitorinfo");
        jMenuItem1.setBorder(new javax.swing.border.MatteBorder(null));
        jMenuItem1.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("visitor");
        setPreferredSize(new java.awt.Dimension(1280, 1024));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        finishButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        finishButton.setText("Next");
        finishButton.setName("end"); // NOI18N
        finishButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                finishButtonMouseClicked(evt);
            }
        });
        finishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishButtonActionPerformed(evt);
            }
        });

        name.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        name.setForeground(new java.awt.Color(51, 153, 255));
        name.setName("name"); // NOI18N
        name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nameMouseExited(evt);
            }
        });
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        company.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        company.setForeground(new java.awt.Color(0, 153, 0));
        company.setName("company"); // NOI18N
        company.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                companyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                companyMouseExited(evt);
            }
        });
        company.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyActionPerformed(evt);
            }
        });

        NameLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        NameLabel.setForeground(new java.awt.Color(51, 153, 255));
        NameLabel.setText("Name ");

        companyLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        companyLabel.setForeground(new java.awt.Color(0, 153, 0));
        companyLabel.setText("Company");

        countryLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        countryLabel.setForeground(new java.awt.Color(153, 0, 153));
        countryLabel.setText("Country");

        visitorLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        visitorLabel.setForeground(new java.awt.Color(255, 51, 0));
        visitorLabel.setText("Visitor Attend");

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("Please Enter Your Details");

        reception.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        reception.setForeground(new java.awt.Color(255, 51, 0));
        reception.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Anna persson", "Lars Nilsson", "Eva sevensson" }));
        reception.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptionActionPerformed(evt);
            }
        });

        country.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        country.setForeground(new java.awt.Color(153, 0, 153));
        country.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sweden", "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Anguilla", "Antigua and Barbuda", "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan", "Bolivia", "Bosnia-Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burma", "Burundi", "Cambodia", "Cameroon", "Canada", "Cape Verde", "Central African Republic", "Chad", "Chile", "China", "Colombia", "Comoros", "Congo", "Congo Dem. Republic", "Costa Rica", "Croatia", "Cuba", "Cyprus", "Czech Republic", "Denmark", "Djibouti", "Dominican Republic", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Ethiopia", "Fiji", "Finland", "France", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Holy See (Vatican City)", "Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel", "Italy", "Ivory Coast", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg", "Macedonia", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall", "Mauritania", "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Morocco", "Mozambique", "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Korea", "Norway", "Oman", "Pakistan", "Palau", "Panama", "Papua-New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal", "Qatar", "Romania", "Russia", "Rwanda", "San Marino", "Sao Tomé and Principe", "Saudi Arabia", "Senegal", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Korea", "Spain", "Sri Lanka", "St.Kitts e Nevis", "St.Lucia", "St.Vincent e Grenadine", "Sudan", "Suriname", "Swaziland", "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu", "Ukraine", "Uganda", "United Arab Emirates", "United Kingdom", "Uruguay", "USA", "Uzbekistan", "Vanuatu", "Venezuela", "Vietnam", "Western Samoa", "Yemen", "Yugoslavia", "Zambia", "Zimbabwe" }));
        country.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectoop/Combitech2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        adminButton.setBackground(new java.awt.Color(255, 255, 255));
        adminButton.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        adminButton.setForeground(new java.awt.Color(255, 0, 51));
        adminButton.setText("ADMINISTRATOR");
        adminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButtonActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 204));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        namsuggestion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        namsuggestion.setForeground(new java.awt.Color(255, 153, 51));

        companySuggestion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        companySuggestion.setForeground(new java.awt.Color(255, 0, 0));

        time.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        time.setForeground(new java.awt.Color(0, 204, 51));
        time.setText("Time");

        date.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        date.setForeground(new java.awt.Color(255, 102, 0));
        date.setText("Date");

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setText("Date");

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 51));
        jLabel4.setText("Time");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(countryLabel)
                                    .addComponent(visitorLabel)
                                    .addComponent(companyLabel)
                                    .addComponent(NameLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(namsuggestion, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(country, 0, 0, Short.MAX_VALUE)
                                        .addComponent(reception, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(company, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
                                        .addComponent(name))))
                            .addComponent(jButton1))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(422, 422, 422)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(577, 577, 577)
                        .addComponent(adminButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(companySuggestion, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(finishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(254, 254, 254))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(165, 165, 165))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(time, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namsuggestion, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(company, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(companyLabel))
                .addGap(18, 18, 18)
                .addComponent(companySuggestion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(country, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(countryLabel)
                        .addGap(8, 8, 8)))
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reception, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(visitorLabel))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(finishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(adminButton)
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel1))
        );

        name.getAccessibleContext().setAccessibleDescription("please");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void finishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishButtonActionPerformed


        String nam = name.getText();
        String com = company.getText();



        String countr = country.getSelectedItem().toString();

        String visitorAttendent = reception.getSelectedItem().toString();
        try {

            Class.forName("com.mysql.jdbc.Driver").newInstance();
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/visitor_info", "root", "root");
            Statement st = con.createStatement();
            System.out.println("Connected");

        //    JOptionPane.showMessageDialog(this, "Connection succesful");

            sql = "insert into info (date,time,name,company,country,visitor_attendent)values(" +"'"+ dat +"'"+","+"'"+tim+"'"+","+ "'" + nam + "'" + "," + "'" + com + "'" + "," + "'" + countr + "'" + "," + "'" + visitorAttendent + "'"+")";

          
            
            st.executeUpdate(sql);

            ResultSet rss = st.executeQuery("select * from info");
            while (rss.next()) {
                System.out.println(" name " + rss.getString("name") + " company " + rss.getString("company") + " country " + rss.getString("country"));
            }



        } catch (Exception ex) {
            System.out.println("Failed to connect." + ex);
            JOptionPane.showMessageDialog(this, "Error in connection");
        }

        verify ll = new verify();
        ll.main(args);
        
        close();
        
        
    }//GEN-LAST:event_finishButtonActionPerformed

    private void companyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_companyActionPerformed

    private void countryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countryActionPerformed

    private void receptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_receptionActionPerformed

    private void finishButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_finishButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_finishButtonMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void adminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButtonActionPerformed

        verify nn = new verify();
        String[] args = null;
        nn.main(args);
        
        close();
        // TODO add your handling code here:
    }//GEN-LAST:event_adminButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        welcome ver = new welcome();
        String[] args = null;
        ver.main(args);
        
        close();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameMouseEntered
        // TODO add your handling code here:
        
        namsuggestion.setText("Enter your firstname and lastname here");
    }//GEN-LAST:event_nameMouseEntered

    private void nameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameMouseExited
        // TODO add your handling code here:
        
           namsuggestion.setText("");
    }//GEN-LAST:event_nameMouseExited

    private void companyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_companyMouseEntered
        // TODO add your handling code here:
           companySuggestion.setText("Enter your Company name here");
        
    }//GEN-LAST:event_companyMouseEntered

    private void companyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_companyMouseExited
        // TODO add your handling code here:
        
          companySuggestion.setText(" ");
    }//GEN-LAST:event_companyMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
         UIManager.setLookAndFeel("com.jtattoo.plaf.smart.SmartLookAndFeel");
        
        
        
        
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(visitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(visitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(visitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(visitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new visitor().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel NameLabel;
    private javax.swing.JButton adminButton;
    public static javax.swing.JTextField company;
    public static javax.swing.JLabel companyLabel;
    private javax.swing.JLabel companySuggestion;
    private javax.swing.JComboBox country;
    public static javax.swing.JLabel countryLabel;
    private javax.swing.JLabel date;
    public static javax.swing.JButton finishButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuItem jMenuItem1;
    public static javax.swing.JTextField name;
    private javax.swing.JLabel namsuggestion;
    private javax.swing.JComboBox reception;
    private javax.swing.JLabel time;
    public static javax.swing.JLabel visitorLabel;
    // End of variables declaration//GEN-END:variables
}
